language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=29e8796e57a400fa2b7138b0f1832e3d6553886ef46c6dc5ab88ea7d621768d3
rvm:
  - 2.2.8
  - 2.2.3
  - 2.3.0
  - 2.4.0
  - 2.5.1
sudo: false
